### ISSUE TITLE
Only first selectable_scatter_plot visible in R Markdown document

### ISSUE THREAD

**Issue by jessakay** [Alanocallaghan/plotlyutils#3]
Thanks for putting together this super useful package! I had a really hard time getting selectable axes working with plotly itself but your `selectable_scatter_plot()` has made it a breeze.

However, when I tried to include multiple such plots in a R Markdown document, only the first one is visible. To troubleshoot, I tried first looking at my browser console but didn't notice any errors. Upon a closer inspection, it seems like only the first instance has an actual `plot` div in addition to the `options` div, but the second one is completely missing `plot`. But when I tried checking the intermediate `.md` file, the two instances looked largely identical, so I'm at a lost as to why the second one won't produce an actual plot.

Attached is an example (with the issue reproducible on multiple machines), and I would really appreciate your help or any pointers for how to further diagnose the issue

[test.Rmd](https://github.com/Alanocallaghan/plotlyutils/files/7109092/test.Rmd.md)

**Comment by Alanocallaghan** [comment]
Hey, thanks for flagging this! I think I'd never actually included multiple plots on one HTML page before, oops!

Should be fixed now. Problem was I had a line that was returning the first "plot" ID div on the page, which obviously isn't ideal when creating the 2nd plot.

**Comment by jessakay** [comment]
Works great! Thanks for the quick fix

**Comment by cbroeckl** [comment]
I just had the same problem and upgrading to the latest version fixed it.  many thanks for this package - this is fantastic, and will make reports so much more dynamic!

**Comment by cbroeckl** [comment]
@Alanocallaghan - correction.  The test.Rmd document supplied by @jessakay appears to function at first, but the first plot is not dynamic - you can select variables for the x and y axes, but when selecting variables for plot 1, the plot only changes for plot 2.  i am assuming the desired behavior is that changing variables/colors for plot 1 changes only plot one display.   Thanks again.

**Comment by Alanocallaghan** [comment]
Should be fixed now (fingers crossed). Some weirdness going on with the plot reference updating which I have hopefully solved

**Comment by cbroeckl** [comment]
Looks like that did the trick!  Thanks!
