### ISSUE TITLE
Getting plotly to play nice with pkgdown on Github Pages

### ISSUE THREAD

**Issue by bryanhanson** [Alanocallaghan/plotlyutils#5]
I'm having trouble getting `plotly` figures to show up in vignettes made with `pkgdown` and served on Github Pages.  I noticed you have accomplished this with https://alanocallaghan.github.io/plotlyvignettes/ but I don't see any vignette code to go with that page.  I was hoping to see how you did it.

In my own case, I have a vignette that when rendered locally as html with plotly figures works correctly.  But when rendered via `pgkdown` on Github Pages the figures are not showing up as you can see [here](https://bryanhanson.github.io/LearnPCA/articles/Vig_05_Visualizing_PCA_3D.html)

I had this working in the past but some change in some package broke things.  I asked a question on [SO](https://stackoverflow.com/q/71832517/633251).

I'm hoping you can point me in the right direction.

**Comment by Alanocallaghan** [comment]
The short answer is that site was built a long time ago. If I regenerate it, some stuff is missing and/or broken from the pkgdown site, and I don't have the time to check what/why/how

**Comment by Alanocallaghan** [comment]
Oh, and the vignette code is here: https://github.com/Alanocallaghan/plotlyvignettes

**Comment by bryanhanson** [comment]
Thank you, that's what I was looking for!
